### ISSUE TITLE
IPD First Mockup Feedback

### ISSUE THREAD

**Issue by ifirmawan** [akvo/idh-ipd#46]
## Todo

- [ ] Remove hover on intro image
- [ ] align images with IDH Comms
- [ ] CHANGE TEXT -“are unable to achieve a sustainable income” change to living income.
- [x] Add legend
- [ ] Add company name in the cases, after crop name to make it more prominant
- [ ] Average for all the boxes except Living income benchmark
- [ ] Add stacked chart for living income gap (like 2scale)
- [ ] Display % of living income gap
- [ ] Add popup if country is not clickable (No Access)
- [ ] Share of households earning an income above the LI benchmark
- [ ] % of total HH income from focus crop
- [ ] Living Income Gap Percentage (To be Added)
- [ ] If Chart is empty show message "XXX cannot be computed because of missing data"
- [ ] If Chart is empty in benchmark, add the message to x axis
- [ ] Change x axis label: [Country] Average in [Crop]
- [ ] Comparing Living Income Benchmark
- [ ] Comparing the Living Income gap
- [ ] Fix Chart (average should be includes the selected company too)
- [ ] Hide Menu but keep component
- [ ] Include a download function for the visuals (simple visual, not report)
- [ ] Hide 'income drivers' tab, include actual values for these 5 indicators in the benchmarking page (compare with country/sector average) 
- [ ] replace "other income" with "non-focus crop income"
